name: text-simplifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - streamlit
  - transformers
  - stanza
  - gtts
  - pydub
  - pyttsx3

  - pip
  - pip:
      - re
      - bert_score
      - rouge-score
      - wrapt
      - gast
